// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public string Ciud_Id { get; set; }
        public string Ciud_Descripcion { get; set; }
        public string Esta_Id { get; set; }
        public bool? Ciud_Estado { get; set; }
        public int Ciud_Creacion { get; set; }
        public DateTime Ciud_FechaCreacion { get; set; }
        public int? Ciud_Modificacion { get; set; }
        public DateTime? Ciud_FechaModificacion { get; set; }

        public virtual tbUsuarios Ciud_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ciud_ModificacionNavigation { get; set; }
        public virtual tbEstados Esta { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}