// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbDiagnosticos
    {
        public tbDiagnosticos()
        {
            tbDietas = new HashSet<tbDietas>();
            tbEntrenamientos = new HashSet<tbEntrenamientos>();
        }

        public int Diag_Id { get; set; }
        public string Pers_Identidad { get; set; }
        public int EsSa_Id { get; set; }
        public decimal? Diag_Peso { get; set; }
        public bool? Diag_Estado { get; set; }
        public int Diag_Creacion { get; set; }
        public DateTime Diag_FechaCreacion { get; set; }
        public int? Diag_Modificacion { get; set; }
        public DateTime? Diag_FechaModificacion { get; set; }

        public virtual tbUsuarios Diag_CreacionNavigation { get; set; }
        public virtual tbUsuarios Diag_ModificacionNavigation { get; set; }
        public virtual tbEstadosSalud EsSa { get; set; }
        public virtual ICollection<tbDietas> tbDietas { get; set; }
        public virtual ICollection<tbEntrenamientos> tbEntrenamientos { get; set; }
    }
}