// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbDietas
    {
        public int Diet_Id { get; set; }
        public int Diag_Id { get; set; }
        public int Alim_Id { get; set; }
        public string Diet_Detalle { get; set; }
        public bool? Diet_Estado { get; set; }
        public int Diet_Creacion { get; set; }
        public DateTime Diet_FechaCreacion { get; set; }
        public int? Diet_Modificacion { get; set; }
        public DateTime? Diet_FechaModificacion { get; set; }

        public virtual tbAlimentos Alim { get; set; }
        public virtual tbDiagnosticos Diag { get; set; }
        public virtual tbUsuarios Diet_CreacionNavigation { get; set; }
        public virtual tbUsuarios Diet_ModificacionNavigation { get; set; }
    }
}