// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbEntrenamientos
    {
        public int Entr_Id { get; set; }
        public int Diag_Id { get; set; }
        public int Ejer_Id { get; set; }
        public decimal? Entr_Peso { get; set; }
        public decimal? Entr_Duracion { get; set; }
        public int? Entr_Repeticiones { get; set; }
        public int? Entr_Sets { get; set; }
        public string Entr_Detalle { get; set; }
        public bool? Entr_Estado { get; set; }
        public int Entr_Creacion { get; set; }
        public DateTime Entr_FechaCreacion { get; set; }
        public int? Entr_Modificacion { get; set; }
        public DateTime? Entr_FechaModificacion { get; set; }

        public virtual tbDiagnosticos Diag { get; set; }
        public virtual tbEjercios Ejer { get; set; }
        public virtual tbUsuarios Entr_CreacionNavigation { get; set; }
        public virtual tbUsuarios Entr_ModificacionNavigation { get; set; }
    }
}