// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbEnfermedades
    {
        public tbEnfermedades()
        {
            tbEnfermedadesPorPersona = new HashSet<tbEnfermedadesPorPersona>();
        }

        public int Enfe_Id { get; set; }
        public string Enfe_Descripcion { get; set; }
        public bool? Enfe_Estado { get; set; }
        public int Enfe_Creacion { get; set; }
        public DateTime Enfe_FechaCreacion { get; set; }
        public int? Enfe_Modificacion { get; set; }
        public DateTime? Enfe_FechaModificacion { get; set; }

        public virtual tbUsuarios Enfe_CreacionNavigation { get; set; }
        public virtual tbUsuarios Enfe_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedadesPorPersona> tbEnfermedadesPorPersona { get; set; }
    }
}