// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbEstados
    {
        public tbEstados()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public string Esta_Id { get; set; }
        public string Esta_Descripcion { get; set; }
        public bool? Esta_Estado { get; set; }
        public int Esta_Creacion { get; set; }
        public DateTime Esta_FechaCreacion { get; set; }
        public int? Esta_Modificacion { get; set; }
        public DateTime? Esta_FechaModificacion { get; set; }

        public virtual tbUsuarios Esta_CreacionNavigation { get; set; }
        public virtual tbUsuarios Esta_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}