// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int PaRo_Id { get; set; }
        public int Pant_Id { get; set; }
        public int Rol_Id { get; set; }
        public bool? PaRo_Estado { get; set; }
        public int PaRo_Creacion { get; set; }
        public DateTime PaRo_FechaCreacion { get; set; }
        public int? PaRo_Modificacion { get; set; }
        public DateTime? PaRo_FechaModificacion { get; set; }

        public virtual tbUsuarios PaRo_CreacionNavigation { get; set; }
        public virtual tbUsuarios PaRo_ModificacionNavigation { get; set; }
        public virtual tbPantallas Pant { get; set; }
        public virtual tbRoles Rol { get; set; }
    }
}