// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbEnfermedadesPorPersona = new HashSet<tbEnfermedadesPorPersona>();
        }

        public string Pers_Identidad { get; set; }
        public string Pers_PrimerNombre { get; set; }
        public string Pers_SegundoNombre { get; set; }
        public string Pers_PrimerApellido { get; set; }
        public string Pers_SegundoApellido { get; set; }
        public string Pers_Sexo { get; set; }
        public decimal Pers_Altura { get; set; }
        public DateTime? Pers_Nacimiento { get; set; }
        public int TiSa_Id { get; set; }
        public int? Usua_Id { get; set; }
        public int EsCi_Id { get; set; }
        public string Ciud_Id { get; set; }
        public bool? Pers_Estado { get; set; }
        public int Pers_Creacion { get; set; }
        public DateTime Pers_FechaCreacion { get; set; }
        public int? Pers_Modificacion { get; set; }
        public DateTime? Pers_FechaModificacion { get; set; }

        public virtual tbCiudades Ciud { get; set; }
        public virtual tbEstadosCiviles EsCi { get; set; }
        public virtual tbUsuarios Pers_CreacionNavigation { get; set; }
        public virtual tbUsuarios Pers_ModificacionNavigation { get; set; }
        public virtual tbTiposSangre TiSa { get; set; }
        public virtual tbUsuarios Usua { get; set; }
        public virtual ICollection<tbEnfermedadesPorPersona> tbEnfermedadesPorPersona { get; set; }
    }
}