// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_CreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_ModificacionNavigation = new HashSet<tbUsuarios>();
            tbAlimentosAlim_CreacionNavigation = new HashSet<tbAlimentos>();
            tbAlimentosAlim_ModificacionNavigation = new HashSet<tbAlimentos>();
            tbCiudadesCiud_CreacionNavigation = new HashSet<tbCiudades>();
            tbCiudadesCiud_ModificacionNavigation = new HashSet<tbCiudades>();
            tbDiagnosticosDiag_CreacionNavigation = new HashSet<tbDiagnosticos>();
            tbDiagnosticosDiag_ModificacionNavigation = new HashSet<tbDiagnosticos>();
            tbDietasDiet_CreacionNavigation = new HashSet<tbDietas>();
            tbDietasDiet_ModificacionNavigation = new HashSet<tbDietas>();
            tbEjerciosEjer_CreacionNavigation = new HashSet<tbEjercios>();
            tbEjerciosEjer_ModificacionNavigation = new HashSet<tbEjercios>();
            tbEnfermedadesEnfe_CreacionNavigation = new HashSet<tbEnfermedades>();
            tbEnfermedadesEnfe_ModificacionNavigation = new HashSet<tbEnfermedades>();
            tbEnfermedadesPorPersonaEnPe_CreacionNavigation = new HashSet<tbEnfermedadesPorPersona>();
            tbEnfermedadesPorPersonaEnPe_ModificacionNavigation = new HashSet<tbEnfermedadesPorPersona>();
            tbEntrenamientosEntr_CreacionNavigation = new HashSet<tbEntrenamientos>();
            tbEntrenamientosEntr_ModificacionNavigation = new HashSet<tbEntrenamientos>();
            tbEstadosCivilesEsCi_CreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEsCi_ModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosEsta_CreacionNavigation = new HashSet<tbEstados>();
            tbEstadosEsta_ModificacionNavigation = new HashSet<tbEstados>();
            tbEstadosSaludEsSa_CreacionNavigation = new HashSet<tbEstadosSalud>();
            tbEstadosSaludEsSa_ModificacionNavigation = new HashSet<tbEstadosSalud>();
            tbPantallasPant_CreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPant_ModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPaRo_CreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPaRo_ModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPersonasPers_CreacionNavigation = new HashSet<tbPersonas>();
            tbPersonasPers_ModificacionNavigation = new HashSet<tbPersonas>();
            tbPersonasUsua = new HashSet<tbPersonas>();
            tbRolesRol_CreacionNavigation = new HashSet<tbRoles>();
            tbRolesRol_ModificacionNavigation = new HashSet<tbRoles>();
            tbTiposSangreTiSa_CreacionNavigation = new HashSet<tbTiposSangre>();
            tbTiposSangreTiSa_ModificacionNavigation = new HashSet<tbTiposSangre>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public byte[] Usua_Clave { get; set; }
        public bool? Usua_IsAdmin { get; set; }
        public int? Rol_Id { get; set; }
        public bool? Usua_Estado { get; set; }
        public int Usua_Creacion { get; set; }
        public DateTime Usua_FechaCreacion { get; set; }
        public int? Usua_Modificacion { get; set; }
        public DateTime? Usua_FechaModificacion { get; set; }

        public virtual tbRoles Rol { get; set; }
        public virtual tbUsuarios Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_CreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAlimentos> tbAlimentosAlim_CreacionNavigation { get; set; }
        public virtual ICollection<tbAlimentos> tbAlimentosAlim_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_CreacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDiagnosticos> tbDiagnosticosDiag_CreacionNavigation { get; set; }
        public virtual ICollection<tbDiagnosticos> tbDiagnosticosDiag_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDietas> tbDietasDiet_CreacionNavigation { get; set; }
        public virtual ICollection<tbDietas> tbDietasDiet_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEjercios> tbEjerciosEjer_CreacionNavigation { get; set; }
        public virtual ICollection<tbEjercios> tbEjerciosEjer_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedades> tbEnfermedadesEnfe_CreacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedades> tbEnfermedadesEnfe_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedadesPorPersona> tbEnfermedadesPorPersonaEnPe_CreacionNavigation { get; set; }
        public virtual ICollection<tbEnfermedadesPorPersona> tbEnfermedadesPorPersonaEnPe_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEntrenamientos> tbEntrenamientosEntr_CreacionNavigation { get; set; }
        public virtual ICollection<tbEntrenamientos> tbEntrenamientosEntr_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosSalud> tbEstadosSaludEsSa_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosSalud> tbEstadosSaludEsSa_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaRo_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaRo_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonasPers_CreacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonasPers_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonasUsua { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_CreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposSangre> tbTiposSangreTiSa_CreacionNavigation { get; set; }
        public virtual ICollection<tbTiposSangre> tbTiposSangreTiSa_ModificacionNavigation { get; set; }
    }
}